//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFPoprijonok.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class products_short_k_import
    {
        public string Наименование_продукции { get; set; }
        public string Тип_продукции { get; set; }
        public int Артикул { get; set; }
        public byte Количество_человек_для_производства { get; set; }
        public byte Номер_цеха_производства { get; set; }
        public string Минимальная_цена_для_агента { get; set; }
    }
}
